Seometa
pcl-labs/vodworks-storyblok pull request #8
Opened 2021-07-11 15:57 UTC by paulchrisluke

im adding some head stuff in prep to follow meta addition guides

2021-07-12 17:06 UTC, paulchrisluke commented
note, I've linked partner page images in this PR as well

2021-07-12 17:36 UTC, paulchrisluke commented
https://github.com/pcl-labs/vodworks-storyblok/issues/11 completed

2021-07-15 04:16 UTC, giteshk11 requested changes

2021-07-15 04:16 UTC, giteshk11 commented on pages/partner/index.vue
> +          to="https://phnompenh.impacthub.net/khmer-tourism-for-the-future/?utm_source=vodworks&utm_medium=referral&utm_campaign=our-partners-page"
If its an external link please replace NuxtLink with `<a href>`

2021-07-15 04:16 UTC, giteshk11 commented on pages/partner/index.vue
> +        <NuxtLink
Same here as well

2021-07-15 04:16 UTC, giteshk11 commented on pages/partner/index.vue
> +        <NuxtLink
Here also

2021-07-15 04:16 UTC, giteshk11 commented on pages/partner/index.vue
> +        <NuxtLink
Here also

2021-07-26 12:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pcl-labs/vodworks-storyblok?pullRequest=8) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/pcl-labs/vodworks-storyblok?pullRequest=8) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: paulchrisluke<br/>:x: Gitesh Khurani<br/><hr/>**Gitesh Khurani** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pcl-labs/vodworks-storyblok?pullRequest=8) it.</sub>

2021-07-26 12:15 UTC, merged